#include <iostream>
#include <string>
#include "prints.h"
using namespace std;

void print_board(char **board, int ROWS, int COLS)
{
    // text symbols generated by https://www.madeintext.com/text-symbols/
    // beginning space & column labels
    cout << "  ";
    for (int i = 0; i < COLS; i++)
    {
        if (i < 10)
            cout << "  " << i << " ";
        else
            cout << "  " << i;
    }
    cout << endl;

    // separator
    cout << "  ┼–";
    for (int i = 0; i < COLS; i++)
    {
        if (i != COLS - 1)
            cout << "––┼–";
        else
            cout << "––┤";
    }
    cout << endl;

    for (int i = 0; i < ROWS; i++)
    {
        // row labels + separator
        cout << char(i + 'a') << " │ ";

        // mine + border
        for (int j = 0; j < COLS; j++)
        {
            if (board[i][j] == '0')
                cout << ' ' << " │ ";
            else
                cout << board[i][j] << " │ ";
        }
        cout << endl;

        // border breathing space
        if (i != ROWS - 1)
            cout << "  ┼–";
        else
            cout << "  ╵ ";
        for (int j = 0; j < COLS; j++)
        {
            if (i == ROWS - 1 && j == COLS - 1)
                cout << "  ╵ ";
            else if (j == COLS - 1)
                cout << "––┼";
            else if (i != ROWS - 1)
                cout << "––┼–";
            else
                cout << "  ╵ ";
        }
        cout << endl;
    }
}

void print_instructions()
{
    cout << "█▀▄▀█ █ █▄░█ █▀▀ █▀ █░█░█ █▀▀ █▀▀ █▀█ █▀▀ █▀█" << endl;
    cout << "█░▀░█ █ █░▀█ ██▄ ▄█ ▀▄▀▄▀ ██▄ ██▄ █▀▀ ██▄ █▀▄\n" << endl;
    string input;
    cout << "WIN by uncovering all the unarmed mines \nLOSE by stepping on an armed mine \n \n";

    cout << "each mine will have a number indicating how many BOMBS are around it \n e.g. a mine with the number 2 indicates that there are 2 bombs next to it \n \n";

    cout << "UNCOVER by typing in the coordinates of the mine \n e.g. >> a0 \n \n";

    cout << "add and remove FLAGS with ? to note down possible armed locations and prevent tripping them \n e.g. >> ?a0 \n \n";

    cout << "Enter any value to return to menu" << endl;

    cout << ">> ";
    cin >> input;
}